title: "Reeshad Khan, Ph.D."
description: "Efficient AI (EdgeAI) & Autonomous Systems Perception — BEV, radar–vision fusion, RAW-to-task co-design, real-time deployment."
url: "https://reeshad-khan.github.io"
markdown: kramdown
plugins: []

mapmyvisitors_id: RvwUjT-32klShlktnWdZZoFCfgll2rWHBcYMt66bQlk
flagcounter_id: KIl
