title: "Reeshad Khan, Ph.D."
description: "Computer vision and autonomous systems researcher focused on efficient 3D perception, BEV-based autonomous perception and planning, multisensor fusion, and robust learning under noisy and resource-constrained sensing conditions. "
url: "https://reeshad-khan.github.io"
markdown: kramdown
plugins: []

mapmyvisitors_id: RvwUjT-32klShlktnWdZZoFCfgll2rWHBcYMt66bQlk
flagcounter_id: KIl
